on: [push, pull_request]
name: Test
jobs:
  version-matrix:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.21, 1.22]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: make test-coverage
